### ISSUE TITLE
About the way to use this repo

### ISSUE THREAD

**Issue by MADONOKOUKI** [justayak/cabbage#10]
Sorry.
I can't understand which file lead to do execution of tracking by using the detection data and the nerwork python file

If anyone know how to use this repo, please teach me

**Comment by shensheng27** [comment]
MultiplePeopleTracking.py

**Comment by MADONOKOUKI** [comment]
@shensheng27 
```
Traceback (most recent call last):
  File "MultiplePeopleTracking.py", line 5, in <module>
    from cabbage.features.GenerateFeatureVector import pairwise_features
  File "/Users/kokimadono/Downloads/cabbage/cabbage/features/GenerateFeatureVector.py", line 4, in <module>
    from cabbage.features.deepmatching import DeepMatching
  File "/Users/kokimadono/Downloads/cabbage/cabbage/features/deepmatching.py", line 6, in <module>
    from pppr import aabb
ModuleNotFoundError: No module named 'pppr'
```

**Comment by MADONOKOUKI** [comment]
Thank you for teaching me and is it ok to tell me how to import the repository of the pppr?

**Comment by MADONOKOUKI** [comment]
And also do you know where the setting.txt is exsist?

**Comment by shensheng27** [comment]
see readme of the repo, bash install.sh will meet your need

**Comment by MADONOKOUKI** [comment]
@shensheng27 thanks, I'll try to do that.

**Comment by MADONOKOUKI** [comment]
@shensheng27 
I executed the install.sh ando can install it.
After that 
```
cabbage git/master*
❯ python3 MultiplePeopleTracking.py
Using TensorFlow backend.
```
But nothing will occur just say 'Using Tensorflow backed'
So Do you mind if I ask how to get the tracking result from it?

**Comment by MADONOKOUKI** [comment]
And also I got an error...
```
/Users/kokimadono/Downloads/cabbage/src/cabbage.cpp:3:10: fatal error: 'andres/graph/graph.hxx' file not
      found
#include "andres/graph/graph.hxx"
1 error generated.
make[2]: *** [CMakeFiles/Sample.dir/src/cabbage.cpp.o] Error 1
make[1]: *** [CMakeFiles/Sample.dir/all] Error 2
make: *** [all] Error 2
```

**Comment by shensheng27** [comment]
It takes days to generate feature on single video, so i think this repo is more for study lmp rather than any practical use.
I suggest try iou tracker first for practical use, or rewrite the repo for your lmp version.

**Comment by gyc521zsc** [comment]
> It takes days to generate feature on single video, so i think this repo is more for study lmp rather than any practical use.
> I suggest try iou tracker first for practical use, or rewrite the repo for your lmp version.
