### ISSUE TITLE
final trajectories

### ISSUE THREAD

**Issue by aminshabani** [justayak/cabbage#3]
Thanks for your nice implementation. I have a question for the final part.
The referenced paper said that they estimate a smoothed trajectory from the detections that belongs to the same cluster, by using the code from [Continuous energy minimization for multitarget tracking](https://ieeexplore.ieee.org/document/6520846/). Did you use the same method for finding the trajectories which are depicted in the readme file's figure? Can you add the code for that part as well ?!

**Comment by jutanke** [comment]
Hi, thanks for the interest in the implementation. We did not smooth the trajectories due to time constraints and, if I recall correctly, the reference implementation for the smoothing is in Matlab which would have been a bit of a hassle to interop with python.

**Comment by aminshabani** [comment]
Yes, I understand. I saw it now... Thanks for your kind answer.

**Comment by shensheng27** [comment]
@jutanke @aminshabani Hi.
From the milan's source code i didn't find corresponding smooth code block alone.
From the source paper there is no stand clone track refine/postprocess step too.
Have any idea for how to smooth the result?
Thanks

**Comment by aminshabani** [comment]
Hi,
I also didn't find any source code independently. As I understand, in LMP, they said that they used the milan's work for each trajectory separately. Therefore, you can just link the Matlab code and run it on every trajectory.
